# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6d6da2cd5c91aae36f240c97fb8d639b94cc983b4cf3039cffd9fe25f5297d1654982788bb91e4e39d948ffb09ac78d71aa18a13cfb45fea28ea2d8ef349e2e

test:
  secret_key_base: 6b0a811ae8449a9128cb333046f56ac1dc0d465a3168b95badaa8ec2b431ffae867a3d9a95b6211ec2e1d8a4bd053a3a9d5b11be4b2ab96c680bd700d918c8bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
